# Generated by Django 3.0.9 on 2020-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0002_auto_20200803_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(to='wedding_app.OrderItem'),
        ),
    ]
