# Generated by Django 3.0.9 on 2020-08-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0004_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_stock_quantity',
            field=models.IntegerField(default=1000),
        ),
    ]
