# Generated by Django 3.0.9 on 2020-08-10 16:44
import json
from django.db import migrations
from django.utils.text import slugify
from wedding_app.models import Item


def populate_items(apps, schema_editor):
    Item = apps.get_model('wedding_app', 'Item')
    with open('wedding_project/product.json') as json_file:
        data = json.load(json_file)
        for item in data:
            try:
                price = int(item['price'].split('.')[0])
            except (IndexError, ValueError):
                price = 0

            Item.objects.create(
                pk=item['id'], name=item['name'], brand=item['brand'], in_stock_quantity=item['in_stock_quantity'],
                price=price, slug=slugify(item['name']), description='Please add description')


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0005_item_in_stock_quantity'),
    ]

    operations = [
        migrations.RunPython(populate_items),
    ]
